-- Tạo database
CREATE DATABASE QuanLyBongDa;
GO

-- Sử dụng database
USE QuanLyBongDa;
GO

-- Tạo bảng ThuocTinh (Thông tin thực thể)
CREATE TABLE ThuocTinh (
    MaDoi char(3),
    TenDoi nvarchar(50),
    MaTD char(2),
    Ngay date,
    Gio time,
    DoBanThang tinyint
);
GO

-- Tạo bảng Doi
CREATE TABLE Doi (
    MaDoi char(3) PRIMARY KEY,
    TenDoi varchar(50)
);
GO

-- Tạo bảng TranDau
CREATE TABLE TranDau (
    MaTD char(2) PRIMARY KEY,
    MaSan varchar(10),
    Ngay date,
    Gio time
);
GO

-- Tạo bảng CT_TranDau (Chi tiết trận đấu)
CREATE TABLE CT_TranDau (
    MaTD char(2),
    MaDoi char(3),
    SoBanThang tinyint,
    PRIMARY KEY (MaTD, MaDoi),
    FOREIGN KEY (MaTD) REFERENCES TranDau(MaTD),
    FOREIGN KEY (MaDoi) REFERENCES Doi(MaDoi)
);
GO

-- Chèn dữ liệu vào bảng Doi
INSERT INTO Doi (MaDoi, TenDoi) VALUES
('VN', N'Việt Nam'),
('LA', N'Lào'),
('TL', N'Thái Lan'),
('CPC', N'Campuchia');

-- Chèn dữ liệu vào bảng TranDau
INSERT INTO TranDau (MaTD, MaSan, Ngay, Gio) VALUES
('01', 'MOD', '2017-08-14', '15:00'),
('02', 'NAS', '2017-08-16', '17:00'),
('03', 'MOD', '2017-08-16', '15:00'),
('04', 'IMO', '2017-08-18', '19:00');

-- Chèn dữ liệu vào bảng CT_TranDau
INSERT INTO CT_TranDau (MaTD, MaDoi, SoBanThang) VALUES
('01', 'VN', 3),
('01', 'TL', 1),
('02', 'VN', 5),
('02', 'LA', 0),
('03', 'TL', 3),
('03', 'CPC', 3),
('04', 'TL', 2),
('04', 'LA', 0);
GO

-- Kiểm tra dữ liệu
SELECT * FROM Doi;
SELECT * FROM TranDau;
SELECT * FROM CT_TranDau;


---------------------------------------------------------------------------------------------------------------



CREATE DATABASE QUANLYBONGDA_0525
GO

USE QUANLYBONGDA_0525
GO

CREATE TABLE DOI(
	MADOI CHAR(3) NOT NULL,
	TENDOI NVARCHAR(30)
)
GO

CREATE TABLE TRANDAU(
	MATD CHAR(2) NOT NULL,
	MASAN VARCHAR(3),
	NGAY DATE,
	GIO TIME(0)
)
GO

CREATE TABLE CT_TRANDAU(
	MATD CHAR(2) NOT NULL,
	MADOI CHAR(3) NOT NULL,
	SOBANTHANG TINYINT
)
GO

ALTER TABLE DOI ADD CONSTRAINT PK_DOI PRIMARY KEY (MADOI)
GO

ALTER TABLE TRANDAU ADD CONSTRAINT PK_TRANDAU PRIMARY KEY (MATD)
GO

ALTER TABLE CT_TRANDAU ADD CONSTRAINT PK_CT_TRANDAU PRIMARY KEY (MATD, MADOI)
GO


INSERT INTO DOI(MADOI, TENDOI) VALUES
('VN', N'VIỆT NAM'),
('LA', N'LÀO'),
('TL', N'THÁI LAN'),
('CPC', N'CAMPUCHIA')
GO

INSERT INTO TRANDAU(MATD, MASAN, NGAY, GIO) VALUES
('01', 'MOD', '2017-08-14', '15:00'),
('02', 'NAS', '2017-08-16', '17:00'),
('03', 'MOD', '2017-08-16', '15:00'),
('04', 'IMO', '2017-08-18', '19:00')
GO

INSERT INTO CT_TRANDAU(MATD, MADOI, SOBANTHANG) VALUES
('01', 'VN', 3),
('01', 'TL', 1),
('02', 'VN', 5),
('02', 'LA', 0),
('03', 'TL', 3),
('03', 'CPC', 3),
('04', 'TL', 2),
('04', 'LA', 0);
GO

-- TRUY VẤN DỮ LIỆU

-- 1. IN SỐ TRẬN MÀ MỖI ĐỘI ĐÃ THI ĐẤU. HIỂN THỊ: MADOI, TENDOI
SELECT CT.MADOI, D.TENDOI, COUNT(CT.MATD) AS SOTRAN
FROM CT_TRANDAU CT
JOIN DOI D ON CT.MADOI = D.MADOI
GROUP BY CT.MADOI, D.TENDOI
GO

-- 2. IN KẾT QUẢ TRẬN ĐẤU THEO TỈ SỐ "01 | VN-TL | 3-1"
SELECT T1.MATD AS [MÃ TRẬN],
       CONCAT(T1.MADOI, '- ', T2.MADOI) AS [ĐỘI TRẬN ĐẤU],
       CONCAT(T1.SOBANTHANG, '-', T2.SOBANTHANG) AS [TỈ SỐ]
FROM CT_TRANDAU T1
JOIN CT_TRANDAU T2 ON T1.MATD = T2.MATD AND T1.MADOI > T2.MADOI 
ORDER BY T1.MATD ASC
GO

-- 3. IN KẾT QUẢ MỖI TRẬN THEO ĐIỂM
-- MATRAN | DOI | DIEM
-- 01	  | VN  | 3
-- 01	  | TL  | 0
-- THẮNG 1 TRẬN +3 ĐIỂM, HUỀ +1 ĐIỂM, THUA O ĐIỂM
SELECT T1.MATD AS [MATRAN],
       T1.MADOI AS [DOI],
    CASE WHEN T1.SOBANTHANG > T2.SOBANTHANG THEN 3 
         WHEN T1.SOBANTHANG = T2.SOBANTHANG THEN 1  
         WHEN T1.SOBANTHANG < T2.SOBANTHANG THEN 0  
    END AS [DIEM]
FROM CT_TRANDAU T1
JOIN CT_TRANDAU T2 ON T1.MATD = T2.MATD AND T1.MADOI != T2.MADOI  
ORDER BY T1.MATD, T1.MADOI
GO

-- 4. IN RA MÃ ĐỘI, TÊN ĐỘI, TỔNG ĐIỂM SỐ
-- VN | VIỆT NAM | 6
SELECT D.MADOI,D.TENDOI,
    SUM(CASE WHEN T1.SOBANTHANG > T2.SOBANTHANG THEN 3 
             WHEN T1.SOBANTHANG = T2.SOBANTHANG THEN 1  
             WHEN T1.SOBANTHANG < T2.SOBANTHANG THEN 0 
        END
    ) AS [TONGDIEM]
FROM CT_TRANDAU T1
JOIN CT_TRANDAU T2 ON T1.MATD = T2.MATD AND T1.MADOI != T2.MADOI  
JOIN DOI D ON T1.MADOI = D.MADOI
GROUP BY D.MADOI, D.TENDOI
ORDER BY TONGDIEM DESC
GO

-- 5. IN MÃ ĐỘI, TÊN ĐỘI VÀ TỔNG SỐ ĐIỂM
-- VN | VIỆT NAM | 6
SELECT D.MADOI, D.TENDOI,
    SUM(CASE WHEN T1.SOBANTHANG > T2.SOBANTHANG THEN 3 
             WHEN T1.SOBANTHANG = T2.SOBANTHANG THEN 1  
             WHEN T1.SOBANTHANG < T2.SOBANTHANG THEN 0 
        END) AS [TONGDIEM]
FROM CT_TRANDAU T1
JOIN CT_TRANDAU T2 ON T1.MATD = T2.MATD AND T1.MADOI != T2.MADOI  
JOIN DOI D ON T1.MADOI = D.MADOI
GROUP BY D.MADOI, D.TENDOI
ORDER BY TONGDIEM DESC
GO

-- 7. HIỂN THỊ CÁC TRẬN CHƯA ĐÁ
SELECT CONCAT(D1.MADOI, ' - ', D2.MADOI) AS [TRANCHUADA]
FROM DOI D1
JOIN DOI D2 ON D1.MADOI > D2.MADOI
LEFT JOIN (
    SELECT CT1.MADOI AS DOI1, CT2.MADOI AS DOI2
    FROM CT_TRANDAU CT1
    JOIN CT_TRANDAU CT2 ON CT1.MATD = CT2.MATD AND CT1.MADOI != CT2.MADOI
) T ON (D1.MADOI = T.DOI1 AND D2.MADOI = T.DOI2) 
    OR (D1.MADOI = T.DOI2 AND D2.MADOI = T.DOI1)
WHERE T.DOI1 IS NULL
ORDER BY [TRANCHUADA]
GO